---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/has-tests: true
    apps.tanzu.vmware.com/workload-type: web
  name: app-name
  namespace: my-apps
spec:
  build:
    env:
    - name: NODE_ENV
      value: production
    - name: GENERATE_SOURCEMAP
      value: "false"
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER_ROOT
      value: build
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
